<?php
/**
 * @file
 * Code for the ...
 * on demand to save memory consumption during normal site operation.
 */

/**
 * Adds the menu tab for its page.
 */
function permissions_tree_menu() {
    $items['admin/people/permissions/tree'] = array(
      'title' => 'Tree',
      'description' => 'Tree view by role of all enabled permissions.',
      'page callback' => 'permissions_tree_page',
      'access arguments' => array('administer site configuration'),
      'type' => MENU_LOCAL_TASK,
   );  
   return $items;
}


/**
 * Implements the tree view by user.
 */
function permissions_tree_page() {
	// get array of roles names
   $result = db_select('role', 'r')
      ->fields('r', array('rid', 'name'))
      ->execute();
   while ($record = $result->fetchAssoc()) {
   	$roles[$record['rid']] = $record['name'];
   }
   // gather all permissions ordered
   $result = db_select('role_permission', 'rp')
      ->fields('rp', array('rid', 'permission', 'module'))
      ->orderBy('rid', 'ASC')
      ->orderBy('module', 'ASC')
      ->execute();
   $output = '';
   $last = array('rid' => -1, 'permission' => '', 'module' => '');
   $num = 0;
   while ($record = $result->fetchAssoc()) {
   	$num++;
   	if ($record['rid'] != $last['rid']) {
      	// close previous role table
      	if ($last['rid'] != -1) {
            $output .= "</tbody></table>\n";
      	   $last['module'] = '';
      	}
      	// new role table
      	$output .= '<table id="rid-'.$record['rid'].'"><tbody>
';
      }
      if ($record['module'] != $last['module']) {
      	if ($last['rid'] != -1) {
      	   $output .= "</td></tr>\n";
      	} 
       	// new module title row
       	$output .= _form_html_element('row', 0, $record);
      }
     	$output .= _form_html_element('item', $num, $record);
   	$last = $record;
   }
   $output .= "</tbody></table>\n";
   
   $outarr = explode('<table id="rid-', $output);
   unset($outarr[0]);
   foreach ($outarr as $k=>$table) {
      $pagearr['role-'.$k] = array(
         'fieldset' => array(
            '#type' => 'fieldset',
            '#title' => $roles[$k],
            '#attributes' => array('class' => array('collapsible', 'collapsed')),
            'content' => array(
               '#markup' => '<table id="rid-'.$table,
            ),
         ),
         '#attached' => array(
            'js' => array(
               'misc/collapse.js',
               'misc/form.js',
            ),
            'css' => array(
               drupal_get_path('module', 'permissions_tree').'/permissions_tree.css',
            ),
         ),
      );
   }
   return $pagearr;  
}


/**
 * Helper function.
 */
function _form_html_element($element, $number, $row) {
   switch($element) {
   	case 'row':
         $markup = '<tr><td class="module-row" colspan="2">'.$row['module'].'</td></tr>
<tr class="even"><td class="checkbox permission">';
      break;
   	case 'item':
         $markup = ' <div class="float-inline"><input disabled="disabled" id="'.$row['module'].'-permission-'.$number.'" name="modules['.$row['module'].']['.$number.'][enable]" value="1" checked="checked" class="form-checkbox" type="checkbox"><label for="'.$row['module'].'-permission-'.$number.'">'.$row['permission'].'</label></div>';
      break;
   }
   return $markup;
}
